### ISSUE TITLE
Fibaro UBS (FGBS-001) with new ST app

### ISSUE THREAD

**Issue by cipnt** [cjcharles0/SmartThings#14]
Hi Chris,
Any change of updating this to work with the new SmartThings app?
In the new app there is no option to create the child devices and the SmartThings Classic has now been discontinued.
I'm surprised Fibaro hasn't published an official device handler for this...
Thanks!

**Comment by cjcharles0** [comment]
Feel free to push a change to make it create child devices in the updated() function. I am not actively spring this any more as I don't have a UBS any more and am not using ST very actively now

**Comment by cipnt** [comment]
For anyone that might have this issue, to create the child devices you can use the simulator in the IDE:
- Login to [SmartThings IDE](https://graph.api.smartthings.com/)
- Go to My Device Handlers and select your Fibaro UBS
- In the code editor page, at the top-right corner select Simulator which will bring a side panel
- Select the actual Fibaro UBS device not the default virtual device
- You will then have the normal buttons which would have been available in the SmartThings Classic app, including the createChildDevices

Hope this helps

**Comment by cjcharles0** [comment]
Ive actually just updated the device handler so it supports the new app, today!
