### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by chittbhardwa** [cjcharles0/SmartThings#16]
Seeing this error: 

Org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed: script_dth_metadata_9e202c55_0185_4acb_95b6_e236758258ac: 696: expecting '(', found 'chosenmode' @ line 696, column 9. switch chosenmode { ^ 1 error

When creating a new device handler for Thermostat using this code - https://raw.githubusercontent.com/cjcharles0/SmartThings/master/HeatmiserNeoThermostat/Device-NeoThermostat

Thanks

**Comment by cjcharles0** [comment]
Thanks for raising it, now fixed.
Strange that ST is now enforcing this check, they never used to.
