### ISSUE TITLE
trying to update 

### ISSUE THREAD

**Issue by thefunkygibbon** [cjcharles0/SmartThings#18]
hi I'm trying to update as I don't think I've updated since I bought the kit from you a bunch of years back ,  but when I try adding the ino.bin file into the update firmware it just times out the page and when I check again it hasn't rebooted or anything so I'm guessing nothing has happened.  am I supposed to add it to the firmware bit or the filesystem bit?

the interface doesnt seem to give a code version number so I can't really tell.

any hints would be nice.   I'm guessing there is no incentive to update the code yourself as I'm assuming you have moved on from powermax or something but thanks for the effort a few years ago :-)

**Comment by cjcharles0** [comment]
What do you need updating in it? Or do you mean to support the new ST? My powermax is my favourite smarthome integration even today, but I've moved to hubitat where I've continued developing it. Sadly none of those improvements would help with ST support

**Comment by thefunkygibbon** [comment]
I don't use st at all either any more. I use home assistant .    but your firmware using mqtt is still relavent .
my point was that I was trying to update the firmware as it says the latest bin file was updated 2 years ago.  and given I bought the kit about 6 years ago, I figured it was about time I updated it.  but it can't.

**Comment by cjcharles0** [comment]
It should be possible, and I think somebody has done the basics of it
working with HA, through mqtt already. If suggest taking the latest bin
file from my hubitat repo rather than from the ST one you've commented in.

**Comment by thefunkygibbon** [comment]
nah I've had it working via mqtt on home assistant fine for a few years. that's all good.   literally just wanting to update your esp8826 code as I assume you've improved things in the last 6 years right?

**Comment by thefunkygibbon** [comment]
both bin files look identical and we're updated 2 years ago.

**Comment by cjcharles0** [comment]
I do have more changes recently to include bypass and other features but I
haven't uploaded them, so perhaps 2 years is the latest published one. You
can see compile date in the Wemos and that should give you an indication of
current version.

As for why it's not updating I'm not totally sure, except the fact that age
may have resulted in some changes to file system and hence the update will
not load, but that would surprise me.

What feature are you looking for and why are you looking to update? I tend
to view this as just a risky process unless you want something new.

**Comment by thefunkygibbon** [comment]
well i've not really got any clue as to what features you've added in recent years.  i'm fine with updating things and am not risk averse like that.  generally there are simple ways to roll back, such as an esp device where things are pretty transient and its just a matter of re-flashing the firmware with the previous one. 

if you don't think that there are any aspects of the esp code which would be of any use for mqtt or generally speaking then i'll just knock it on the head.   I'll try again when i get home as i was trying to do it via vpn and on mobile (isnt usually a problem).

**Comment by thefunkygibbon** [comment]
ok i've updated via remote desktop now and it seems ok using the latest fw from the hubitat branch.  it did seem to reset the mqtt settings (and it might be clearer if you added in the config "MQTT server IP Address" rather than using the "Smart Home Controller IP" for that as the config seems to have been wiped (luckily it connected to wifi again fine and got the same IP address) ... unless that was something to do with accidently clicking on the "?X=Y - inactivity_seconds, ip_for_st, port_for_st, mqtt_username, mqtt_password]  whatever that button means.  :-)

thanks again for your efforts on this

**Comment by cjcharles0** [comment]
Yes I havent worked out why it sometimes wipes config, I think its because
Arduino Studio stores the parameters slightly differently in different
versions, even if there are no other changes. Happy to add some
clarification to the text strings.

The X=Y page is just a way of configuring the key parameters through URL,
which is easier than trying to change things on the settings page,
especially if it is HA/Hubitat/... which is trying to set the config. Just
visiting the page wouldnt do anything unless you specified parameters too -
e.g. ?inactivity_seconds=50 at the end of the URL would change the relevant
setting.

If you use bypass or instant mode then you might want the latest version
that I will release soon, but if not then there is probably not much
changing (Im still working to get Powermaster integration to work better as
the majority of time spent on this project)
