### ISSUE TITLE
can't get classic app to work

### ISSUE THREAD

**Issue by oc999** [cjcharles0/SmartThings#4]
hi, everything went fine until step 10... I see the options (I'm using an iphone) but when I click on them, nothing happens. I'm not sure if this is  because it doesn't work on the iphone or not, but right now I have the hub connected but no thermostats. 
Is there any way that I can add the thermostats without using the classic app - either on the new app or online? thanks in advance for any ideas!

**Comment by cjcharles0** [comment]
Have you got any spaces in your thermostat names? Suggest putting this on the Smartthings forum as it is easier to add images/screen shots and discuss

**Comment by oc999** [comment]
Hi, no, it doesn’t respond to any of the clicks I try and do on the classic app. The formatting is all wrong too. Think it may be a version issue?

**Comment by cjcharles0** [comment]
Please add a post on this thread on the Smartthings forum so it helps other users and you can add images of the settings screen in the app and web IDE. Plus also the Live Logging screen when you press refresh IPs or create thermostat children
