### ISSUE TITLE
Restarting MQTT Server does not initialize reconnection.

### ISSUE THREAD

**Issue by endor-force** [cjcharles0/SmartThings#7]
When restarting MQTT Server the code will not reconnect.

The only way i found for reconnection is to go to /advanced in web ui and just submit the page again.

**Before restart of MQTT server:**
Setings.useMQTT: 1
mqtt_last_reconnect: 0
mqtt_setup: 1
mqtt.connected: 1
mqtt.state: 0

**After restart of MQTT server:**
Setings.useMQTT: 1
mqtt_last_reconnect: 697162 (and increasing)
mqtt_setup: 1
mqtt.connected: 0
mqtt.state: -2

**Comment by cjcharles0** [comment]
It's this in the 2.3 build?

**Comment by endor-force** [comment]
I'm compiling in arduino IDE, tried both with esp8266 2.3 and latest 2.6.3 with same behaviour.
It's just like it needs the mqtt setup to be re-initialized.

https://github.com/knolleary/pubsubclient/blob/master/src/PubSubClient.h
state -2 = MQTT_CONNECT_FAILED

I'm thinking, maybe we could add some conditions in the loop
instead of having just  `if (!mqtt_setup)`

It could be something like this to re-initialize the mqtt connection.
`if (!mqtt_setup || mqtt.state() == -2 || mqtt.state() > 0)`

**Comment by endor-force** [comment]
Tried with these conditions now and it works.
When the mqtt server is restarted/offline the mqtt.state is set to -2.

So it seems to rely on something in the mqtt setup to be performed to enable reconnection (setCallback or setServer)..

**Comment by endor-force** [comment]
setCallback is already in mqttreconnect so it must rely on setServer i guess. 

But the reconnect is not working as intended i guess, since mqtt_last_reconnect is not reset by this:
```
            if (mqttreconnect()) {
              mqtt_last_reconnect = 0;
            }
```

**Comment by endor-force** [comment]
Created PR #9

**Comment by cjcharles0** [comment]
Cool, this is good debugging, were you just printing the data to a webpage while testing the different behaviour?

Yes, the advanced page submission does do a full reset, but annoying and strange that it isnt doing that naturally.

Thanks I will review asap and merge.

**Comment by endor-force** [comment]
Yes I was adding it to the main html temporarily. 
Considered of maybe adding a separate debug json stats page for checking variable values, maybe a future addition. ;)
